### ISSUE TITLE
Devanagari: vowels over the hanging line+candrabindu intersect in document fonts

### ISSUE THREAD

**Issue by marekjez86** [notofonts/devanagari#3]
copied from https://github.com/googlei18n/noto-alpha/issues/206

Imported from [Google Code issue notofonts/noto-fonts#206](https://code.google.com/a.google.com/p/noto-alpha/issues/detail?id=206) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-04-18T01:57:00.000Z:

---

The sequence DDA+AU+CANDRABINDU (0921,094C,0901) in Noto Sans Devanagari results in the AU vowel and the CANDRABINDU intersecting.

See sample rendering from Noto, together with renderings from SIL's Annapurna and Microsoft's Utsaah and Nirmala.

This issue is especially important for Nepali, as it commonly uses candrabindu in its normal orthography.

This also happens with the other vowels going over the hanging line: II, SHORT E, E, AI, CANDRA O, SHORT O, and O.

In the UI fonts, there is another bug (issue notofonts/khmer#12) that predicts me from testing this at the moment, but after fixing that issue, the UI fonts should also be tested to make sure the glyphs don't intersect.

Comment [#2](https://code.google.com/p/noto-alpha/issues/detail?id=206#c2) originally posted by jelle.bosma@monotypeimaging.com on 2014-04-18T07:17:59.000Z:

---

This is not a bug of Noto, but a design decision to make a ligature of the marks. Similar to the reph, which joins with the vowel in order not to end up on the next syllable. In the other three fonts the candrabindu is too far to the right and might be covered by an i-vowel or another top mark on the following syllable. In Noto it might still touch an i-vowel or a mark to the right, but you can always recognise it. Which is definitely not the case in the other three fonts! 

nirmala.png
![nirmala](https://cloud.githubusercontent.com/assets/9939212/8630608/ca82cb30-271c-11e5-9e5f-19e37b35a1f1.png)

noto.png
![noto](https://cloud.githubusercontent.com/assets/9939212/8630610/d5dca6c2-271c-11e5-90a4-ff6524c046ff.png)

sil.png
![sil](https://cloud.githubusercontent.com/assets/9939212/8630613/df6d3760-271c-11e5-9f7a-849b079280da.png)

utsaah.png
![utsaah](https://cloud.githubusercontent.com/assets/9939212/8630615/ede5e29c-271c-11e5-84df-ae641c0f5be5.png)
--- dougfelt commented on Jul 10
This is still an issue.

It seems that one could let the candrabindu be farther to the right when there was no mark for it to interfere with, and only use the squeezed position when necessary.  This would involve taking more context into account.  What do the other fonts do?  Does text with interfering marks occur frequently?
--- JelleBosmaMT commented on Jul 11
This is NOT an issue!

**Comment by simoncozens** [comment]
I believe this has now been fixed in v2.006.
