### ISSUE TITLE
Indesign crashing with glyph sequence औँ

### ISSUE THREAD

**Issue by visionario2** [notofonts/devanagari#31]
Font from https://notofonts.github.io/, version 2.0.3

  1. Steps to reproduce
Insert the Nepali word बनाऔँ in Indesign, apply world-ready composer, and Noto Devanagari font.
  3. Observed results
Indesign crashes
  5. Expected results
Word rendering correctly
  7. Additional information 
I can't say for sure that the problem isn't Indesign, but other Devanagari fonts work fine. I think it's the last two letters that are causing the problem.

**Comment by simoncozens** [comment]
If a font *crashes* InDesign, that's definitely an InDesign bug. But that is still pretty weird.

**Comment by visionario2** [comment]
Yes, must be an Indesign problem - with Harfbuzz enabled, the problem does not occur.
