### ISSUE TITLE
Noto Devanagari : Incorrect rendering of रॢ & रॣ

### ISSUE THREAD

**Issue by Abhay2Agarwal** [notofonts/devanagari#32]
Fonts:
- Noto Sans Devanagari
- Noto Serif Devanagari 

Bug:
- Incorrect rendering of the following:
र + ॢ = रॢ
र + ॣ = रॣ

Source: fonts.google.com

Few Devanagari fonts renders it correctly, & I am sharing screenshots.

- Red : Noto Sans Devanagari

- Green : Mukta, another Devanagari font, that renders correctly. That is how Noto Sans Devanagari is expected to render.

![Screenshot_20230222_214501_Chrome.jpg](https://user-images.githubusercontent.com/26118420/221391436-5fc72a27-ed54-4f5e-a480-994e5f2c9734.jpg)

![Screenshot_20230222_214140_Chrome.jpg](https://user-images.githubusercontent.com/26118420/221391440-9f8fa247-0ac8-4a9b-9e59-bc3f04bbadb3.jpg)

Kindly consider fixing this.

Furthermore, do consider adding support for all the Devanagari characters supported by the latest version of Unicode.

**Comment by simoncozens** [comment]
I notice that Tiro Devanagari Hindi and Tiro Devanagari Sanskrit (by @tiroj) render these differently; the Hindi version renders as Noto currently does (ra with a subscript), and the Sanskrit version renders as you are asking for (vocalic l/r with reph). John is usually quite thoughtful and I think this distinction was probably made for a reason.

I wonder if we want to use the reph rendering only when the language is set to Sanskrit.

**Comment by tiroj** [comment]
I strongly recommend using the shaping with reph for any generic Devanagari font. The Tiro Hindi font only provides full shaping for Hindi character sequences, so not for the long vocalic vowels. It does implement the reph shaping for रृ.
<img width="59" alt="image" src="https://user-images.githubusercontent.com/5614500/223477217-75addab4-e1ca-4dbf-918f-561b89784a2a.png">

**Comment by Abhay2Agarwal** [comment]
> I notice that Tiro Devanagari Hindi and Tiro Devanagari Sanskrit (by @tiroj) render these differently; the Hindi version renders as Noto currently does (ra with a subscript), and the Sanskrit version renders as you are asking for (vocalic l/r with reph). John is usually quite thoughtful and I think this distinction was probably made for a reason.
> 
> I wonder if we want to use the reph rendering only when the language is set to Sanskrit.




*Brother ऌ & ॡ are not used in Hindi. Do it Mukta/Tiro Sanskrit way (the way i have mentioned).*

**Comment by Abhay2Agarwal** [comment]
> I notice that Tiro Devanagari Hindi and Tiro Devanagari Sanskrit (by @tiroj) render these differently; the Hindi version renders as Noto currently does (ra with a subscript), and the Sanskrit version renders as you are asking for (vocalic l/r with reph). John is usually quite thoughtful and I think this distinction was probably made for a reason.
> 
> I wonder if we want to use the reph rendering only when the language is set to Sanskrit.

___

Thanks broski i'm glad you addressed :)

___

I urge you to do the same with the Bangla, Gujarati, Odia, & other Siddham derived Brahmic scripts as well, i.e. reph with vocalic r & l, since they all share the same features, & especially while writing in the Sanskrit language.

I genuinely believe it's not really time consuming, so i am hoping for the changes soon 😊

Also, i want to know if there any way to write reph? Since
र + ् + [ZWNJ] = र्‍

It doesn't work for other scripts either
