### ISSUE TITLE
Updated the position of Devanagari Nukta for the Santali language

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/devanagari#36]
Hello. Thank you for providing us with great fonts.
I’d like to report a request from native Santali speakers to update Noto Sans/Serif Devanagari.

Upon that feedback, we did researched regarding the positioning of the Nukta for the Santali language.
In general, we confirmed that the Nukta positioning in Noto Sans/Serif Devanagari is harmonized with [The Unicode Standard, Version 15.0](https://www.unicode.org/versions/Unicode15.0.0/ch12.pdf#page=17), R9 rule (P.17).

**Sample**
आ़का़काो़
आ़: U+0906 (आ), U+093C (़)
का़: U+0915 (क), U+093E(ा) , U+093C(़)
काो़: U+0915(क), U+093E(ा), U+094B(ो), U+093C(़)

Noto Sans Devanagari Regular from this link displays as the following:
https://github.com/notofonts/devanagari/releases/download/NotoSansDevanagari-v2.004/NotoSansDevanagari-v2.004.zip
![NotoSansDevanagari-Regular](https://github.com/notofonts/devanagari/assets/122098208/229b33c4-c635-4a94-9792-1372373eabe1)
Noto Serif Devanagari Regular from this link displays like the following:
https://github.com/notofonts/devanagari/releases/download/NotoSerifDevanagari-v2.004/NotoSerifDevanagari-v2.004.zip
![NotoSerifDevanagari-Regular](https://github.com/notofonts/devanagari/assets/122098208/eac074df-739e-4fbd-8fa0-7fcb04c3a9ec)
However, the Santali speakers who reported this hope that “Nukta is positioned directly under the matra.”
This may be related to the background that Santali was originally written in the Ol Chiki script.
Because of that, they have more vowels than the other Devanagari-based languages, and they therefore use the Nukta in an unusual way.
For example, the old Santali [dictionary](https://archive.org/details/dli.language.2521/page/n13/mode/2up?view=theater) in Devanagari uses inverted ‘i’ to force the Nukta placed under the Matra (vowel sign).

For these reasons, would it be possible to have the Nukta positioning as below, only for the Santali languages? 
We confirmed that the Language System Tag for this language is SAT: https://learn.microsoft.com/en-gb/typography/opentype/spec/languagetags
![suggenstion](https://github.com/notofonts/devanagari/assets/122098208/9d6df272-2e19-4204-a864-525bd41ea3ca)

Thank you for taking this request into consideration.

**Comment by simoncozens** [comment]
This is a great idea, and we will implement this. We're currently expecting some improvements to Noto Devanagari from a supplier, and once that's been delivered I can work on the alternate nukta placement.

**Comment by simoncozens** [comment]
Sorry for the delay; with the fix above, and `lang=sat`, we now get:

![shape](https://github.com/notofonts/devanagari/assets/106728/a38661f7-0877-46c0-a0a3-d46a9db0a543)
![shape](https://github.com/notofonts/devanagari/assets/106728/b63c687c-e773-4037-84f0-8dc56d2b67f7)

We have to do some QA on the semibold changes and then will release a new version.
