### ISSUE TITLE
Incorrect rendering in Photoshop/Illustrator

### ISSUE THREAD

**Issue by curya** [notofonts/devanagari#37]
### Font 
NotoSansDevanagari[wdth,wght].ttf 2.004
NotoSerifDevanagari[wdth,wght].ttf 2.004
NotoSans[wdth,wght].ttf 2.013

### Where the font came from, and when
Github releases

### OS name and version
Windows 10

### Application name and version
Adobe Photoshop 2023
Adobe Illustator 2023

### Issue
I know nothing about Devanagari. I was just checking out this [Wikipedia page](https://en.wikipedia.org/wiki/Complex_text_layout) and decided to copy and paste the word on the top right (द्ध्र्य). See screenshots below. Doesn't work in Adobe software, but renders just fine on fonts.google.com as well as crowbar. It's broken in both Devanagari fonts as well as Latin/Greek/Cyrillic fonts.

  1. Copy the characters into Photoshop/Illustrator.
  2. Observe incorrectness.

### Character data
द + ् + ध + ् + र + ् + य = द्ध्र्य

### Screenshot
Adobe:
![image](https://github.com/notofonts/devanagari/assets/71131343/76ce1b5c-75e6-415b-b91f-a905a6e6d91a)

Fonts.google.com:
![image](https://github.com/notofonts/devanagari/assets/71131343/4cd43c2d-bade-4f32-b5f4-76d52b570c98)
![image](https://github.com/notofonts/devanagari/assets/71131343/3832f6c1-2190-4c99-ad79-c52a8184816c)

Crowbar:
![image](https://github.com/notofonts/devanagari/assets/71131343/32e1681e-6ebe-497e-a37d-6026223fdcf9)
![image](https://github.com/notofonts/devanagari/assets/71131343/c08be6ea-3304-4d44-94e1-f421256ace3c)

EDIT:
Also कि is rendering backwards:
![image](https://github.com/notofonts/devanagari/assets/71131343/7fbbcbb2-b4b9-4766-bcb1-022b4a201549)
When I copy and paste द्ध्र्य, it works fine, but for कि I have to force right-to-left in order for it to appear correctly:
![image](https://github.com/notofonts/devanagari/assets/71131343/d875b051-13a7-41cd-8853-0fafba8f1e7d)

EDIT 2: I just realized that Devanagari is included in Noto Sans Latin/Greek/Cyrillic, but *not* in the Serif version. Shouldn't Devanagari Serif be included?

EDIT 3: I'm not even sure if *any* of the screenshots above are rendering द्ध्र्य correctly. If you look at the picture on the Wikipedia page, it looks nothing like the rendering on fonts.google.com/crowbar. But again, I know nothing about Devanagari...

**Comment by simoncozens** [comment]
> Doesn't work in Adobe software, but renders just fine on fonts.google.com as well as crowbar. 

I'm not surprised about this. Unfortunately you can't just paste text from a different script into Adobe software and expect it to work. Did you [enable Indic Options](https://helpx.adobe.com/in/illustrator/using/asian-scripts.html) and turn on the World Ready Composer?

"This font works but not in Adobe" is an Adobe bug.

> EDIT 2: I just realized that Devanagari is included in Noto Sans Latin/Greek/Cyrillic, but not in the Serif version. Shouldn't Devanagari Serif be included?

*sigh* Technically, Noto LGC should *not* include Devanagari; it's only there in the Google Fonts version for historical reasons (someone once needed Devanagari to work in Google Workspace so they added it to Noto Sans, and now to avoid breaking existing documents we have to keep it there...)

**Comment by curya** [comment]
@simoncozens Actually, that was exactly the issue. I apparently pasted first and *then* turned on indic options. Now pasting into Illustrator works just fine. And apparently, I can just paste straight into Photoshop without changing any settings.

But is there a reason why it doesn't look like the picture on Wikipedia? They look completely different...

Wikipedia:
![image](https://github.com/notofonts/devanagari/assets/71131343/e1c833b0-3289-4863-96e5-8c136b8b2935)

Noto Sans:
![image](https://github.com/notofonts/devanagari/assets/71131343/e46a0168-9dc6-45e6-be7c-156de3087bd9)

**Comment by simoncozens** [comment]
Yes, it depends entirely on the level of conjunct support in the font. This is quite a feature of Devanagari and other Indic scripts - there are an almost unlimited number of conjuncts that you might include in the font, but you have to draw the lime somewhere. We don't include this particular conjunct, and that's not a bug, it's just a scope limitation. See #1 for more details.
