### ISSUE TITLE
NotoSansDevanagari Font's Glyph named 'katadeva' is not working.

### ISSUE THREAD

**Issue by mehulchanpura** [notofonts/devanagari#40]
Font name : NotoSansDevanagari-Regular.ttf & also all styles of NotoSansDevanagari

Font Version : 2.004

Font download from : https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari?subset=devanagari&noto.script=Deva

Download Date : 25 January 2024

Bug : Glyph named 'katadeva' is not working.

Solution : Glyph 'katadeva' is a combination of Glyph 'kaprehalfdeva' & Glyph 'uni0924(त)'. In 'katadeva' Glyph info in the Ligatures option need to add New Ligature, in New Ligature under Subtable need to add " 'cjct' Conjunct Forms lookup 309 subtable " and then under Source Glyph Names need to add " kaprehalfdeva uni0924(त) "

Firstly I want to say Thank You to developers who created this beautiful font and appreciate their hard work.
I am attaching screenshot for to visual result before correction and after correction. This bug is in the every style of NotoSansDevanagari font, above I just mentioned one Regular style because I don't want that list long.
I request developers please make above correction so everyone who is using this font will get proper result.

Thanks again.
![Screenshot 2024-01-25 161646](https://github.com/notofonts/devanagari/assets/57705542/808259f6-96df-4a17-b144-4b5866f9223e)

**Comment by simoncozens** [comment]
Thanks for the bug report. The k-ta ligature *does* work, but only in specific contexts. If your document's language is set to Nepali or Sanskrit, then you will get the ligated form; for Hindi or other languages you will get the half form. (This is true for Noto Serif as well.)

https://github.com/notofonts/devanagari/assets/106728/f2482847-58ca-473a-908c-22986627ecea
