### ISSUE TITLE
The position of Devanagari Nukta with U+0913, U+0914 for the Santali language

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/devanagari#43]
Hello. Thank you for providing us with great fonts.

Thanks for updating on the following issue I posted.
https://github.com/notofonts/devanagari/issues/36
I checked the latest Noto Sans and Serif on this point and report what I noticed.

The post included the following examples.
आ़: U+0906(आ), U+093C(़)

Sorry for the lack of information, but I was hoping that the position of Nukta would be adjusted in the following example as well.

आ़: U+0906(आ), U+093C(़)
ओ़: U+0913(ओ), U+093C(़)
औ़: U+0914(औ), U+093C(़)
आ़ँ: U+0906(आ), U+093C(़), U+0901(ँ)
ओ़ँ: U+0913(ओ), U+093C(़), U+0901(ँ)
औ़ँ: U+0914(औ), U+093C(़), U+0901(ँ)
आ़ं: U+0906(आ), U+093C(़), U+0902(ं)
ओ़ं: U+0913(ओ), U+093C(़), U+0902(ं)
औ़ं: U+0914(औ), U+093C(़), U+0902(ं)

I checked with hb-view and it appears like this:

**Noto Sans v2.006 (language: Santali)**
![image](https://github.com/user-attachments/assets/befea5b3-e9fc-4bdb-b9ab-744d1833298e)

**Noto Serif v2.006 (language: Santali)**
![image](https://github.com/user-attachments/assets/9f1e4953-8b9e-47e0-88d2-7396c9b45c7f)

**Noto Sans v2.006 (language: default)**
![image](https://github.com/user-attachments/assets/a350a760-a9bb-48b7-8934-6cf3dbcf2086)

**Noto Serif v2.006 (language: default)**
![image](https://github.com/user-attachments/assets/6b315ff3-d527-419c-b0da-eae962e6e094)
Thank you for taking this request into consideration.

**Comment by simoncozens** [comment]
The nukta is good now, thanks to your PR, but I am not happy about the position of the candrabindu.
