### ISSUE TITLE
Display issue of Rakar U+094D and U+0930 for the Marathi language

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/devanagari#45]
Hello. Thank you for providing us with great fonts.
I’d like to submit a pull request regarding Noto Sans Devanagari for Marathi language support.

The following characters are displayed correctly in Hindi but not in Marathi.
And the problem occurred in version 2.006, but not in version 2.004.

**Sample**
ड्र ढ्र छ्र ट्र ठ्र ळ्र
ड्र: U+0921(ड), U+094D(्), U+0930(र)
ढ्र: U+0922(ढ), U+094D(्), U+0930(र)
छ्र: U+091B(छ), U+094D(्), U+0930(र)
ट्र: U+091F(ट), U+094D(्), U+0930(र)
ठ्र: U+0920(ठ), U+094D(्), U+0930(र)
ळ्र: U+0933(ळ), U+094D(्), U+0930(र)
(ट्र and ड्र seem to be frequently used letters in Marathi.)

**Fonts**
**Noto Sans Devanagari v2.006**
https://github.com/notofonts/devanagari/releases/download/NotoSansDevanagari-v2.006/NotoSansDevanagari-v2.006.zip

**Noto Sans Devanagari v2.004**
https://github.com/notofonts/devanagari/releases/download/NotoSansDevanagari-v2.004/NotoSansDevanagari-v2.004.zip

**Screenshots**
**Noto Sans v2.006 (language: Marathi)**
![image](https://github.com/user-attachments/assets/f9a4fba7-2811-4c13-9a27-0c25d072a5e1)

**Noto Sans v2.006 (language: Hindi)**
![image](https://github.com/user-attachments/assets/3e25031a-2192-4ff8-99d6-400dd9651be0)

**Noto Sans v2.004 (language: Marathi)**
![image](https://github.com/user-attachments/assets/5fe171df-ba44-4a9c-b4ea-ae8c3da0bfb5)

**Noto Sans v2.004 (language: Hindi)**
![image](https://github.com/user-attachments/assets/15051849-2d16-4015-a8fb-17d4b13bb68a)

Thank you for taking this request into consideration.

**Comment by simoncozens** [comment]
You fixed this!
