### ISSUE TITLE
Positioning of Svarita and anudatta in combination with Visarga in Devanagari 

### ISSUE THREAD

**Issue by sridatta1** [notofonts/devanagari#5]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  >Positioning of Svarita and anudatta in combination with Visarga in Devanagari 

### Font 
  > NotoSansDevanagari-Regular.otf
  > 

### Where the font came from, and when
  > For example:
  >   Site:https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansDevanagari/NotoSansDevanagari-Regular.otf
  >   Date: 2019-07-07 (preferred format)

### Font Version
  > 1.05

### Issue
 > Regarding positioning of vedic marks, wrt visarga.  In encoding order/input the vedic svara should come at the end of syllable ( p460 chapter 12.1 of the core specification). But phonetically here the svara/accent/pitch is associated with the vowel, thus graphically the svarita/anudatta mark should note stand above the visarga. The vedic mark should be placed on the previous consonant/vowel.
![image](https://user-images.githubusercontent.com/23263723/60767621-1491f280-a0d8-11e9-8b6d-61b3af4acd67.png)

Observed results
![image](https://user-images.githubusercontent.com/23263723/60767645-53c04380-a0d8-11e9-80c5-cc70c91c3f48.png)
Expected results
 The vedic mark should be placed on/below the previous consonant/vowel.

Additional information 
![image](https://user-images.githubusercontent.com/23263723/60767665-997d0c00-a0d8-11e9-81f7-f9b0b87d7d95.png)

In printed texts, 
![image](https://user-images.githubusercontent.com/23263723/60767676-b87b9e00-a0d8-11e9-9cb1-7751c2c36863.png)
![image](https://user-images.githubusercontent.com/23263723/60767680-bf0a1580-a0d8-11e9-89b1-21cfce2d8b97.png)
![image](https://user-images.githubusercontent.com/23263723/60767709-fed0fd00-a0d8-11e9-9ec0-408bc5a2b047.png)

In a manuscript
![image](https://user-images.githubusercontent.com/23263723/60767686-d34e1280-a0d8-11e9-8036-274dbdfcc328.png)

### Character data
  >नः॑ यः॑ तः॒ etc.  
Visarga at the end of a syllable  followed by U+0951 DEVANAGARI STRESS SIGN UDATTA : Vedic tone svarita or U+0952 DEVANAGARI STRESS SIGN ANUDATTA : Vedic tone anudatta

**Comment by simoncozens** [comment]
I've fixed this, at least for the Visarga and at least for Noto Sans Devanagari. The fix will go out with the next release, which will be hopefully at the end of next month. If there are similar issues in other scripts, please open an issue in the appropriate script's repo.
