### ISSUE TITLE
Inconsistent kerning of U+0979 DEVANAGARI LETTER ZHA

### ISSUE THREAD

**Issue by dscorbett** [notofonts/devanagari#6]
### Font
NotoSansDevanagari-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/46eb8fa0c46d16a87eee3e763baa3efb7423a8b4/phaseIII_only/unhinted/ttf/NotoSansDevanagari/NotoSansDevanagari-Regular.ttf
Date: 2019-10-20

### Font version
Version 2.000

### Issue
Forms of <i>ža</i> aren’t kerned the same as the analogous forms of <i>ja</i>.

### Character data
ज्कक्ज
U+091C DEVANAGARI LETTER JA
U+094D DEVANAGARI SIGN VIRAMA
U+0915 DEVANAGARI LETTER KA
U+0915 DEVANAGARI LETTER KA
U+094D DEVANAGARI SIGN VIRAMA
U+091C DEVANAGARI LETTER JA
ॹ्कक्ॹ
U+0979 DEVANAGARI LETTER ZHA
U+094D DEVANAGARI SIGN VIRAMA
U+0915 DEVANAGARI LETTER KA
U+0915 DEVANAGARI LETTER KA
U+094D DEVANAGARI SIGN VIRAMA
U+0979 DEVANAGARI LETTER ZHA

### Screenshot
![ज्कक्ज ॹ्कक्ॹ](https://user-images.githubusercontent.com/1124347/67162612-7bf44b00-f333-11e9-9ec9-93ec932d729c.png)

**Comment by simoncozens** [comment]
I've fixed this for the Sans. There's no zha half form in Serif and given the comments above about Avestani maybe that's OK.
