### ISSUE TITLE
Weird spacing effects with ardhavisarga in Noto Serif Devanagari

### ISSUE THREAD

**Issue by NorbertLindenberg** [notofonts/devanagari#9]
Noto Serif Devanagari (version 2.001) shows the characters U+1CF2 VEDIC SIGN ARDHAVISARGA and U+1CF3 VEDIC SIGN ROTATED ARDHAVISARGA with different weird spacing effects in different browsers.

To reproduce, go to
https://lindenbergsoftware.com/google/noto/deva-ardhavisarga.html

The columns for Sans and Serif contain the same character sequences, five times each the characters mentioned above, first by themselves, then bracket by some other Devanagari characters. In the Sans column (using Noto Sans Devanagari), the character are shown five times. In the Serif column (using Noto Serif Devanagari), it often appears that there’s only one character.

Microsoft Edge 44.19041.1.0; EdgeHTML 18.19041; Microsoft Windows 10 version 2004:

<img width="434" alt="Screen Shot 2020-08-19 at 23 10 45" src="https://user-images.githubusercontent.com/216206/90723254-44b33b00-e271-11ea-82c1-819097f0ea6a.png">

Safari 13.1.2 on macOS 10.15.6:

<img width="385" alt="Screen Shot 2020-08-19 at 23 06 11" src="https://user-images.githubusercontent.com/216206/90723485-aa9fc280-e271-11ea-9028-e0d77b2b00d6.png">

Firefox 79.0 on macOS 10.14.6:

<img width="299" alt="Screen Shot 2020-08-19 at 23 13 35" src="https://user-images.githubusercontent.com/216206/90723460-a2478780-e271-11ea-9240-832860dcfcfe.png">

**Comment by simoncozens** [comment]
I've fixed this for the presenting glyphs, but if there are others then yes, a PR would be lovely. (It would be easier to compare the GDEFs with Sans if the glyph names were the same, but that's another issue we need to look into...)
